### ISSUE TITLE
Lazy load images (only load when they come in viewport)

### ISSUE THREAD

**Issue by stvhanna** [revolunet/angular-carousel#183]
Lazy loading the images improves performance, especially when there are many images in the carousel. Thus, this is great feature to have for better user experience.

It would be nice to load the image as they come into the viewport, both from page scroll and carousel index perspective.

It would be nice to implement this feature. :)

Thanks in advance!

**Comment by think2011** [comment]
+1

**Comment by dbelieves** [comment]
is lazy loading available ?
