### ISSUE TITLE
Dynamically disable/enable swipe/next/prev option

### ISSUE THREAD

**Issue by franklinmartinmoses** [revolunet/angular-carousel#217]
I am trying to dynamically disable/enable swipe by setting rn-carousel-swipe = false. But it is not working.
please let me know if anyone got any solution for this.

**Comment by ionescho** [comment]
rn-carousel-locked doesn't work for me..

**Comment by senatwj** [comment]
rn-carousel-locked didn't work for me either.

However, after looking through the source code I found an rn-swipe-disabled attribute which did work.
