### ISSUE TITLE
Is "position: absolute" required on <li> elements ?

### ISSUE THREAD

**Issue by gigmaps** [revolunet/angular-carousel#297]
was struggling to get rn-carousel working correctly 
with the slide positions being all out of wack - until i stumbled across this issue:

is `position: absolute` required on `<li>` elements ?
**or do i have a bug somewhere ?**
...or am I not understanding something basic about css :-/

Nothing mentioned in the (rather scant) documentation...

tried this on the following version ranges with the same result:
- rn-carousel versions 0.3.5 - 0.3.9
- angularjs versions 1.3.0 - 1.3.12

Plunker here showing carousel with and without absolute positioning :
http://plnkr.co/edit/HDp7yfK75gCZUpokaEEZ
Note the gaps in the _non position:absolute_ carousel due to the `display: inline-block` within an `ng-repeat` loop

StackOverflow question here if someone wants the points:
http://stackoverflow.com/questions/28373275

**Comment by revolunet** [comment]
Hi
Did you try with including the rn-carousel.css ?
https://github.com/revolunet/angular-carousel/blob/master/dist/angular-carousel.css

**Comment by gigmaps** [comment]
thanks for the reply - no I didn't - since we have a bunch of custom css within the carousel we don't want changed... 
Is this directive is dependent on an external css file style definition to work correctly ?

**Comment by revolunet** [comment]
the basic positionning/layout is defined in this css and should be namespaced and overridable

**Comment by gigmaps** [comment]
BTW since it's only 1 style required to get the carousel working properly, I'm a little surprised the directive doesn't simply add an element.style of `position: absolute` on the `li` as it does with `display: inline-block;` - which is added manually by the directive, even though it's also included in the CSS class you list above - that would simplify things and allow users to add the CSS if they thought it was useful and/or necessary...
