### ISSUE TITLE
control div inside ul

### ISSUE THREAD

**Issue by octavioamu** [revolunet/angular-carousel#325]
The control (next/ prev) is injecting inside <ul></ul> this should be outside like sibling.

**Comment by revolunet** [comment]
agree

**Comment by sergiy-talashko** [comment]
+

**Comment by alexward1981** [comment]
Totally agree, not only unsemantic but can also cause problems.

**Comment by alexward1981** [comment]
I've fixed this issue and added a pull request, hopefully it will be approved soon.

**Comment by revolunet** [comment]
merged, thank you

**Comment by alexward1981** [comment]
No problem. Do you know when you are going to make the next release to 
bower?

Thanks,

Alex.

**Comment by kamilbrk** [comment]
Just saying, that should have been noted properly in Release notes, rather than "fix #325", as that was a bit of a breaking change for custom CSS styles.

**Comment by alexward1981** [comment]
Yup. My bad, sorry about that, I fixed it on a very busy day, not that that's a valid excuse.
