### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module: function (angular)

### ISSUE THREAD

**Issue by jbarros35** [revolunet/angular-carousel#339]
What does means such error?
  // list of files / patterns to load in the browser
    files: [
      'bower_components/jquery/dist/jquery.js',
     // 'bower_components/crypto-js/sha256.js',
      'bower_components/bootstrap/dist/css/bootstrap.min.css',
      'bower_components/angular-mass-autocomplete/massautocomplete.theme.css',
      'bower_components/ngDialog/css/ngDialog.css',
      'bower_components/ngDialog/css/ngDialog-theme-default.css',
      'bower_components/angular/angular.js',
      'bower_components/angular-route/angular-route.js',
      'bower_components/angular-resource/angular-resource.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'bower_components/angular-sanitize/angular-sanitize.js',
      'bower_components/angular-touch/angular-touch.js',
      'bower_components/angular-loader/angular-loader.js',
      'bower_components/angular-bootstrap/ui-bootstrap-tpls.js',
      'bower_components/requirejs/require.js',
      //'bower_components/requirejs-text/text.js',
      'bower_components/ngstorage/ngStorage.js',
      'bower_components/angular-mass-autocomplete/massautocomplete.js',
      'bower_components/bootstrap/dist/js/bootstrap.js',
      //'bower_components/ngDialog/js/ngDialog.js',
      'bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js',
      'require-config.js',
      'test/test-main.js',
      'login/login.js',
      'layout/menu.js',
      'home/home.js',
      'profile/signup.js',
      'layout/utils.js',
      'app.js',
      'test/*.js',
    ],

**Comment by revolunet** [comment]
mmm i dont see any reference to carousel here.
BTW this error should come from the shifty.js require.js integration

**Comment by revolunet** [comment]
what happened ?

**Comment by jbarros35** [comment]
sorry its a wrong issue, my target is for Karma.
