### ISSUE TITLE
Possible to show more than one carousel item at a time? 

### ISSUE THREAD

**Issue by wanderingstan** [revolunet/angular-carousel#341]
Looking through the docs it doesn't seem possible to have more than one item visible at a time. 

However, the "buffered ngRepeat with custom transition" demo does show the previous and following items, so it seems possible in theory. 

Is it possible to to show more? And if not, consider this a feature request!

I'm looking to migrate away from jQuery where I use the Slick carousel with multiple items:
http://kenwheeler.github.io/slick/

**Comment by revolunet** [comment]
if you arrange your images by "page" you can do it. in this example i was displaying multiples items at once : https://github.com/revolunet/angular-carousel/blob/master/demo/flickr-full/index.html#L85-L95
