### ISSUE TITLE
Angular-carousel  & rn-carousel-controls

### ISSUE THREAD

**Issue by coreysnyder04** [revolunet/angular-carousel#370]
Using rn-carousel-controls causes TypeError: Cannot read property 'length' of undefined when using any ng filters such as orderBy in your forEach. 

```
<ul rn-carousel rn-carousel-controls rn-carousel-index="carouselIndex" class="image" >
    <li ng-repeat="image in images | orderBy:'age'">
        <div class="layer">{{ image.name }}</div>
     </li>
</ul>
```

If I remove either the `rn-carousel-controls` or the ` | orderBy:'age'`the error goes away. 

I believe the error is on [this line](https://github.com/revolunet/angular-carousel/blob/master/dist/angular-carousel.js#L456) where we're calling `scope[repeatCollection.replace('::', '')].length` and that property doesn't exist on the scope so we're calling length of undefined.

**Comment by coreysnyder04** [comment]
Upon looking into this further it looks like the regex which is used to capture `repeatItem` and `repeatCollection` needs some work. [Here's a regex tester showing what is going wrong](https://regex101.com/r/yU6tC0/1).

**Comment by revolunet** [comment]
i think the repeatCollection should be the final, filtered expression souldn't it ? so you get the order you asked in the carousel

can you please test with this change ? https://github.com/revolunet/angular-carousel/commit/0f2b303b37b631461881cab3ddfab1a7dc46a356

**Comment by coreysnyder04** [comment]
I'll try that. Another solution might be to adjust the regex to properly pull out the repeatCollection value. `repeatCollection`. 
Something like this `^\s*(.+?)\s+in\s+(.+?)(?:\s+\S+)*?(?:\s+track\s+by\s+(.+?))?\s*$` 
would take this string `slide in slides | orderBy:'age' track by slide.id`
and assign: 
Group 1: `slide`
Group 2: `slides`
Group 3: `slide.id`

**Comment by coreysnyder04** [comment]
OOh I see what you're saying. When making the regex change and removing that extra info from the `repeatCollection` it breaks when you use the `rn-carousel-buffered` b/c it omits your filtering/sorting/etc.

**Comment by coreysnyder04** [comment]
@revolunet Your solution doesn't work b/c its saved to the scope as the property images. So the `repeatCollection = "images | orderBy:'-age'"` and there isn't a `scope[images | orderBy:'-age']`. Just a `scope.images`. What if after pulling out the repeatCollection w/ with filter-components we then strip out just the collectionName. And then use the collectionName in when setting the `canloop` variable? I can fork it, test it, and submit a pull request.

**Comment by coreysnyder04** [comment]
** EDIT** I lied your solution works just fine. Do you have time to update it? If not I can create a pull request and make that change.

**Comment by coreysnyder04** [comment]
There will be additional work that will need done for this.. The ng-if on the left/right arrows for the controls end up looking like:
`ngIf: carouselIndex < bundleDef.steps | orderBy : 'positionX'.length - 1 || false`

**Comment by coreysnyder04** [comment]
I have a fix for this and it's pretty simple. You just need to wrap some parens around part of the line where `nextSlideIndexCompareValue` is set: 

```
if (iAttributes.rnCarouselControls!==undefined) {
                            // dont use a directive for this
                            var canloop = ((isRepeatBased ? scope.$eval(repeatCollection.replace('::', '')).length : currentSlides.length) > 1) ? angular.isDefined(tAttributes['rnCarouselControlsAllowLoop']) : false;
                            var nextSlideIndexCompareValue = isRepeatBased ? '(' + repeatCollection.replace('::', '') + ').length - 1' : currentSlides.length - 1;
                            var tpl = '<div class="rn-carousel-controls">\n' +
                                '  <span class="rn-carousel-control rn-carousel-control-prev" ng-click="prevSlide()" ng-if="carouselIndex > 0 || ' + canloop + '"></span>\n' +
                                '  <span class="rn-carousel-control rn-carousel-control-next" ng-click="nextSlide()" ng-if="carouselIndex < ' + nextSlideIndexCompareValue + ' || ' + canloop + '"></span>\n' +
                                '</div>';
                            iElement.parent().append($compile(angular.element(tpl))(scope));
                        }
```

**Comment by coreysnyder04** [comment]
@revolunet Hey have you had a chance to review that pull request. If you have any feedback or suggestions I'd be happy to fix whatever.

**Comment by vko-online** [comment]
This is still not working with `angular@1.4.8`

**Comment by mval1002** [comment]
I was still having this issue too (though with Angular 1.5.5) until I installed via the following:

bower install angular-carousel#1.0.1 --save

I don't know if it was grabbing 1.0.0 without that specific target (I only noticed after that 1.0.1 is still numbered the 1.0.0 in the JS file), but this helped me, and it only takes a second to try!
