### ISSUE TITLE
Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by sharduul** [revolunet/angular-carousel#381]
Getting this error when I run:
npm install angular-carousel

Can someone help me here?

**Comment by revolunet** [comment]
works here, which npm version/os do you have ?
```
$ npm install angular-carousel
carousel@1.0.0 /Users/juju/Desktop/tmp/carousel
└── angular-carousel@1.0.1  extraneous

npm WARN EPACKAGEJSON carousel@1.0.0 No description
npm WARN EPACKAGEJSON carousel@1.0.0 No repository field.
```

**Comment by sharduul** [comment]
I am sorry.. It was totally my fault..
I had previous SSL proxy settings made on NPM..

For future reference:
npm config rm proxy
npm config rm https-proxy

This worked for me.

**Comment by revolunet** [comment]
all good :+1:
