### ISSUE TITLE
changing the duration (rn-carousel-auto-slide)

### ISSUE THREAD

**Issue by pliablepixels** [revolunet/angular-carousel#382]
Hello there! 
I am using angular-carousel for my home security app - I have a situation where I need to change the playback speed dynamically. This maps to rn-carousel-auto-slide being changed dynamically.

What would you think is the cleanest way to achieve this? In the code duration is computed at the start of the directive. Is there a way to bind it to the variable I pass it, so if the variable changes this value changes?

I am invoking it this way:
```
<ul rn-carousel rn-carousel-buffered rn-carousel-transition="none" rn-swipe-disabled="true" rn-carousel-index="mycarousel.index" rn-carousel-auto-slide="{{eventSpeed}}" rn-carousel-pause-on-hover">
```
eventSpeed is what needs to change while its playing.

Thanks again for this lovely library.

**Comment by pliablepixels** [comment]
The solution I implemented was to create a factory with a setter and getter for duration and changed the code to use the factory setter/getter --> so that my calling app could change it any time.

**Comment by revolunet** [comment]
Thanks for your suggestion and feedback :) If you have an example code to share, this may be helpful to others... thanks :)

**Comment by pliablepixels** [comment]
Hi @revolunet - my code changes are so horrid you'd probably get shocked looking at it :-)

I added this factory to angular-carousel.js
```
.factory ('carouselControl', function() {
        var stoporplay = false;
        var duration = 0;
        return {

                setDuration: function (val)
                {
                        duration = val;
                },

                getDuration: function ()
                {
                        return duration;
                },

                setStopOrPlay: function(val)
                {
                        stoporplay = val;
                },
                getStopOrPlay: function()
                {
                        return stoporplay;
                },
                isStopped: function()
                {
                        return stoporplay;
                },
               
        }
    })
```

And then  every time you move to the next slide, you use the duration value from the template. Instead, I changed it to 

```
scope.autoSlider = $interval(function() {
                                        //console.log ("setting time to " + mydurms);
                                        if (!locked && !pressed ) {
                                        
                                          scope.nextSlide();
                                        }    
                                        }, carouselControl.getDuration());
```

**Comment by revolunet** [comment]
Thanks for sharing the workaround

In the current code : https://github.com/revolunet/angular-carousel/blob/master/src/directives/rn-carousel.js#L389 the `rn-carousel-auto-slide` attribute expects an integer value at initialisation and cannot be changed later because it use an infinite interval function. Making it tweakable at each interval implies to change that `$interval` to a recurring `$timeout` that could evaluate the `rn-carousel-auto-slide` attribute at each timeout using the `$parse` function (to be able to read the attribute value in the current scope).
