### ISSUE TITLE
Error: the slides collection must be an Array

### ISSUE THREAD

**Issue by danielraban** [revolunet/angular-carousel#392]
I have received this error when using ng-repeat, any suggestion?

**Comment by ScriptMonkey00** [comment]
I got that error when binding incorrectly with a component's variables.  Can you include a code sample, maybe I can help.

**Comment by danielraban** [comment]
I resolved the issue thanks.

**Comment by guicouto** [comment]
I Have the same problem. What is the solution?

**Comment by minhnhat2807** [comment]
If you use AJAX request, should add empty array first
**Example:**
```
$scope.slides = []; ==> for angular-carousel watch this variable
ajax request ==> call back ==> update $scope.slides
```

Hope this help

**Comment by zhujinhu21** [comment]
@danielraban  how did you solve this. i use ajax request to load data
