### ISSUE TITLE
prevent clicks on desktop

### ISSUE THREAD

**Issue by revolunet** [revolunet/angular-carousel#396]
While swiping on desktop, ngTouch triggers a click if your `<li>`has a `ngClick`

Here's a workaround to prevent this unwanted behaviour :

```js
angular.module('xxx')
    .directive('testwipe', function () {
        return {
            restrict: 'A',
            scope: { method: '&testwipe' },
            link: function (scope, element, attrs) {
               
                element.on("mousedown", function (event) {
                    element.unbind("click");
                    element.on("mouseup mousemove", function handler(evt) {
                        if (evt.type === 'mouseup') {
                            // click
                            scope.$apply(scope.method());
                        } else {
                            // drag
                        }
                        element.off("mouseup mousemove", handler);
                    });
                });
            }
        };
    });
```

**Comment by axul** [comment]
Working in latest chrome, safari, internet explorer 11, cordova with android 5.1, if I find something wrong I'll report

**Comment by axul** [comment]
After testing this directive, I can tell this is not a viable solution, sometimes it produces a weird behavior in touch devices. For now, this is working for me: @revolunet 

     .directive('rnCarouselClick', ['$parse', function($parse){
       return {
         compile: function(element, attr) {
           var fn = $parse(attr.sirTap, /* interceptorFn */ null, /* expensiveChecks */ true);
           return function ngEventHandler(scope, element) {
             var click = true;
             element.on('click', function(event) {
               if (click){
                 var callback = function() {
                   fn(scope, {$event:event});
                 };
               scope.$apply(callback);
               }  
             });

             element.on('touchstart mousedown', function(){
               click = true;
             });

             element.on('touchmove mousemove', function(){
               click = false;
             });
           };
         }
       };
     }])

**Comment by revolunet** [comment]
Hi ! Thanks for reporting !

sorry i can't maintain this lib anymore but if someone is motivated, i can give contributors access after a first PR :)
